"""H36 — φ-Spiral Positional Encoding.

A deterministic positional encoding whose trajectory traces a golden
spiral in 3-D and is then lifted to the embedding dimension ``D`` by
a fixed orthonormal projection (or a learnable ``nn.Linear`` when
``learnable=True``).

Position ``k`` contributes the 3-vector ``(cos(k·GA), sin(k·GA),
k/N)``, where ``GA = 2π·(1 - 1/φ) ≈ 137.508°`` is the golden angle and
``N`` is the maximum sequence length. The first two coordinates trace
a unit circle at maximally-irrational angular spacing (phyllotaxis);
the third encodes monotonic "age" along the spiral.

The 3-vector is then projected up to ``D`` dimensions:

* When ``learnable=False`` (default) the projection matrix is a fixed
  ``(3, D)`` orthonormal slice generated by a deterministic seed. The
  projection is *fixed* — the resulting PE is **not** a trainable
  parameter.
* When ``learnable=True`` the helper still produces the deterministic
  3-vector trajectory but the user-facing :class:`GoldenSpiralPE`
  wraps a learnable ``nn.Linear(3, D)`` so gradients flow back into
  the projection while the trajectory itself stays anchored to the
  golden spiral.
"""
from __future__ import annotations

import math
from typing import Optional

import torch
import torch.nn as nn

from .priors import PHI


__all__ = [
    "GOLDEN_ANGLE",
    "golden_spiral_pe",
    "GoldenSpiralPE",
]


GOLDEN_ANGLE: float = 2 * math.pi * (1 - 1 / PHI)


def _fixed_orthonormal_projection(dim: int, seed: int = 0xA17EC) -> torch.Tensor:
    """Return a fixed orthonormal matrix of shape ``(3, dim)``.

    Uses QR decomposition of a deterministic Gaussian matrix so the
    projection is exactly the same across calls and across processes
    (Rule 6 — no silent randomness).
    """
    if dim < 3:
        raise ValueError(f"dim must be >= 3, got {dim}")
    g = torch.Generator().manual_seed(seed)
    rand = torch.randn(dim, 3, generator=g)
    q, _ = torch.linalg.qr(rand, mode="reduced")  # (dim, 3)
    return q.t()  # (3, dim)


def golden_spiral_pe(
    seq_len: int,
    dim: int,
    learnable: bool = False,
    seed: int = 0xA17EC,
) -> torch.Tensor:
    """Produce a ``(seq_len, dim)`` golden-spiral positional encoding.

    Parameters
    ----------
    seq_len : int
        Number of token positions ``N``.
    dim : int
        Embedding dimension ``D``. Must be ``>= 3`` so the 3-D
        trajectory can be embedded.
    learnable : bool, default False
        If ``False``, the returned tensor is a fixed orthonormal lift
        of the 3-vector trajectory. If ``True``, the function instead
        returns just the raw ``(N, 3)`` trajectory matrix — the caller
        is then expected to wrap it in a learnable ``nn.Linear(3, D)``
        (which is what :class:`GoldenSpiralPE` does).
    seed : int, default 0xA17EC
        Deterministic seed for the fixed orthonormal projection.

    Returns
    -------
    torch.Tensor
        Shape ``(seq_len, dim)`` when ``learnable=False``, or
        ``(seq_len, 3)`` when ``learnable=True``.
    """
    if seq_len <= 0:
        raise ValueError(f"seq_len must be positive, got {seq_len}")
    if dim < 3:
        raise ValueError(f"dim must be >= 3, got {dim}")
    k = torch.arange(seq_len, dtype=torch.float32)
    cos_k = (k * GOLDEN_ANGLE).cos()
    sin_k = (k * GOLDEN_ANGLE).sin()
    z_k = k / float(seq_len)
    traj = torch.stack([cos_k, sin_k, z_k], dim=-1)  # (N, 3)
    if learnable:
        return traj
    proj = _fixed_orthonormal_projection(dim, seed=seed)  # (3, D)
    return traj @ proj  # (N, D)


class GoldenSpiralPE(nn.Module):
    """``nn.Module`` wrapper around :func:`golden_spiral_pe`.

    Holds the deterministic ``(seq_len, 3)`` trajectory as a
    non-learnable buffer, a learnable ``nn.Linear(3, dim)`` projection
    (when ``learnable=True``) or a fixed orthonormal projection buffer
    (when ``learnable=False``), and a learnable scalar scale
    initialised to 1.0 so the module's overall magnitude can be
    tuned during training without modifying the trajectory itself.

    ``forward(x)`` adds the PE to a token-stream input ``x`` of shape
    ``(B, N, D)``.
    """

    def __init__(
        self,
        seq_len: int,
        dim: int,
        learnable: bool = False,
        seed: int = 0xA17EC,
    ) -> None:
        super().__init__()
        self.seq_len = seq_len
        self.dim = dim
        self.learnable = learnable
        traj = golden_spiral_pe(seq_len, dim, learnable=True, seed=seed)  # (N, 3)
        self.register_buffer("traj", traj, persistent=True)
        if learnable:
            self.proj = nn.Linear(3, dim, bias=False)
            with torch.no_grad():
                # Initialise from the fixed orthonormal projection so the
                # first forward matches the deterministic helper output.
                self.proj.weight.copy_(_fixed_orthonormal_projection(dim, seed).t())
        else:
            proj = _fixed_orthonormal_projection(dim, seed=seed)  # (3, D)
            self.register_buffer("proj_fixed", proj, persistent=True)
            self.proj = None
        self.scale = nn.Parameter(torch.ones(1))

    def pe(self) -> torch.Tensor:
        """Return the current ``(seq_len, dim)`` PE tensor."""
        if self.learnable:
            return self.scale * self.proj(self.traj)  # type: ignore[union-attr]
        return self.scale * (self.traj @ self.proj_fixed)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.dim() != 3:
            raise ValueError(f"expected (B, N, D), got shape {tuple(x.shape)}")
        B, N, D = x.shape
        if D != self.dim:
            raise ValueError(f"dim mismatch: x has {D}, module has {self.dim}")
        if N > self.seq_len:
            raise ValueError(
                f"sequence length {N} exceeds PE capacity {self.seq_len}"
            )
        pe = self.pe()[:N]  # (N, D)
        return x + pe.unsqueeze(0)
