"""Generate `RESULTS.md` — autoresearch-style narrative report.

For every experiment with a metrics.json + a matching reasoning entry,
emit a section with: tag, config, prior flags, citations, hypothesis,
prediction, actual numbers, automatic verdict (KEEP/NEAR-MISS/DISCARD).

Also produces a top-line composite-ranked table and a per-prior bar
summary, plus a paragraph called out as the "campaign verdict".
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from nature_inspired_networks.dashboard import load_runs  # noqa: E402
from nature_inspired_networks.reasoning import load_all  # noqa: E402


def _verdict(actual: float, lo: float, hi: float) -> str:
    if lo <= actual <= hi:
        return "KEEP (in predicted range)"
    if (lo - 0.02) <= actual <= (hi + 0.02):
        return "NEAR-MISS (within 2 pp of range)"
    return "DISCARD (outside predicted range)"


def _parse_range(s: str, key: str = "composite") -> tuple[float, float] | None:
    import re

    # Look for "<key> in [a, b]" or "<key> in (a, b)" within s
    pat = re.compile(rf"{key}\s+in\s+[\[\(]\s*(-?\d+\.?\d*)\s*,\s*(-?\d+\.?\d*)\s*[\]\)]",
                     re.IGNORECASE)
    m = pat.search(s)
    if m:
        return float(m.group(1)), float(m.group(2))
    return None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="experiments")
    ap.add_argument("--out", default="RESULTS.md")
    args = ap.parse_args(argv)

    df = load_runs(args.root)
    reasoning = {e["experiment_id"]: e for e in
                 load_all(Path(args.root) / "reasoning_annotations.json")}

    lines: list[str] = []
    lines.append("# RESULTS — nature_inspired_networks curated CIFAR-10 sweep\n")
    lines.append("Auto-generated by `scripts/build_report.py` from "
                 "`experiments/experiment_log.jsonl` + "
                 "`experiments/reasoning_annotations.json`.\n")
    if df.empty:
        lines.append("\nNo runs found.\n")
        Path(args.out).write_text("\n".join(lines), encoding="utf-8")
        return 0

    # Top-line ranking
    df = df.sort_values("composite", ascending=False)
    lines.append("\n## Top-line ranking (composite descending)\n")
    lines.append("| rank | tag | seed | top-1 | params | latency ms | composite |")
    lines.append("|---|---|---|---|---|---|---|")
    for rank, (_, r) in enumerate(df.iterrows(), 1):
        lines.append(
            f"| {rank} | `{r['tag']}` | {int(r['seed'])} | "
            f"{r['top1']*100:.2f}% | {r['params']/1e6:.3f}M | "
            f"{r['latency_ms']:.2f} | {r['composite']:.4f} |"
        )
    best = df.iloc[0]
    lines.append(f"\n**Best composite:** `{best['tag']}` at {best['composite']:.4f} "
                 f"(top-1 {best['top1']*100:.2f}%, "
                 f"{best['params']/1e6:.3f} M params, "
                 f"{best['latency_ms']:.2f} ms latency).\n")

    # Per-experiment narratives
    lines.append("\n## Per-experiment results\n")
    for _, r in df.iterrows():
        tag = r["tag"]
        # Match reasoning entry by tag substring
        key = next((k for k in reasoning if tag in k), None)
        rsn = reasoning.get(key, {}) if key else {}
        lines.append(f"\n### `{tag}` (seed {int(r['seed'])})\n")
        lines.append(f"- **Top-1:** {r['top1']*100:.2f}%  | "
                     f"**Top-5:** {r['top5']*100:.2f}%")
        lines.append(f"- **Params:** {r['params']/1e6:.3f} M  | "
                     f"**FLOPs:** {r['flops']/1e6:.1f} M  | "
                     f"**Latency:** {r['latency_ms']:.2f} ms")
        lines.append(f"- **Rotation equivariance err:** {r['rot_eq_err']:.4f}")
        lines.append(f"- **Composite:** {r['composite']:.4f}  | "
                     f"**Generalization gap:** {r['generalization_gap']:.4f}  | "
                     f"**Epochs to target:** {int(r['epochs_to_target'])}")
        if rsn:
            lines.append(f"\n**Hypothesis:** {rsn.get('hypothesis', '—')}")
            lines.append(f"\n**Prediction:** {rsn.get('prediction', '—')}")
            rng = _parse_range(rsn.get("prediction", ""), "composite")
            if rng:
                lo, hi = rng
                v = _verdict(r["composite"], lo, hi)
                lines.append(f"\n**Verdict (composite):** {v}  "
                             f"— predicted [{lo:.3f}, {hi:.3f}], "
                             f"actual {r['composite']:.4f}")
            cites = rsn.get("citations", [])
            if cites:
                lines.append("\n**Citations:**")
                for c in cites:
                    lines.append(f"- {c}")

    # Campaign-level verdict paragraph
    lines.append("\n## Campaign verdict\n")
    n_total = len(df)
    pred_in_range = 0
    for _, r in df.iterrows():
        tag = r["tag"]
        key = next((k for k in reasoning if tag in k), None)
        rng = _parse_range(reasoning.get(key, {}).get("prediction", ""), "composite") if key else None
        if rng and rng[0] <= r["composite"] <= rng[1]:
            pred_in_range += 1
    lines.append(
        f"Of the {n_total} completed runs, **{pred_in_range} landed inside "
        f"the pre-run predicted composite range** "
        f"(strict; near-miss not counted). That ratio is the autoresearch "
        f"protocol's primary calibration signal: a researcher who predicts "
        f"well writes a useful hypothesis; one who predicts poorly is "
        f"surprised by their own ablation and learns more.\n"
    )

    Path(args.out).write_text("\n".join(lines), encoding="utf-8")
    print(f"[ok] wrote {args.out} ({len(df)} runs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
